Fix failure of decoding if the specified encoding is not UTF-8.
tefra/xsdata pull request #934
Opened 2024-02-03 09:49 UTC by skinkie

## 📒 Description

Fix failure of decoding if the specified encoding is not UTF-8.

Resolves https://github.com/tefra/xsdata/issues/932

Resolves #xxxx

## 🔗 What I've Done

Applied the encoding from the configuration to the decode.

## 💬 Comments

What I am still curious about.

1. When the serializer would render to the requested encoding
2. We decoded this to a string
3. Is the output still in th requested encoding? Or should this have remained binary in order to write it to a file in the requested encoding?

## 🛫 Checklist

- [ ] Updated docs
- [ ] Added unit-tests
- [ ] [Sample tests](https://github.com/tefra/xsdata-samples) pass
- [ ] [W3C tests](https://github.com/tefra/xsdata-w3c-tests) pass

2024-02-03 09:50 UTC, tefra requested changes
let's add a relevant test case please

2024-02-03 09:59 UTC, skinkie commented
@tefra which repo / where are the tests stored? The w3c or something different?

2024-02-03 10:27 UTC, tefra commented
> @tefra which repo / where are the tests stored? The w3c or something different?

This repo includes unit tests and a few integration tests.

The w3c [repo ](https://github.com/tefra/xsdata-w3c-tests)is a test running for the official w3 xsd tests.

The samples [repo ](https://github.com/tefra/xsdata-samples), includes various suites with aspects not covered anywhere else, it's also the test ground for different xsdata condegen settings.


I was referring to the https://github.com/tefra/xsdata/blob/main/tests/formats/dataclass/serializers/writers/test_lxml.py, we need to add a test case or update an existing.

2024-02-03 10:46 UTC, skinkie commented
```python
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig
from netex import PublicationDelivery, MultilingualString, DataObjectsRelStructure
from xsdata.models.datatype import XmlDateTime

import codecs

serializer_config = SerializerConfig(ignore_default_attributes=True)
serializer_config.ignore_default_attributes = True
serializer_config.xml_declaration = True
serializer_config.encoding = 'ISO-8859-1'
serializer = XmlSerializer(serializer_config)

publication_delivery = PublicationDelivery(
    publication_timestamp=XmlDateTime.now(),
    participant_ref="Ĥèľló",
    description=MultilingualString(value="UTF-8 to ISO-8859-1"),
    data_objects=DataObjectsRelStructure(choice=[]),
    version="ntx:1.1",
)

output = serializer.render(publication_delivery)

codecs.open('test.xml', 'w', encoding="ISO-8859-1").write(output)
```
Without codecs it outputs again in UTF-8. I think either we need a render which _guarantees_ binary output. Otherwise this results into a fake ISO-8859-1 header, with UTF-8 content:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<ns0:PublicationDelivery xmlns:ns0="http://www.netex.org.uk/netex" version="ntx:1.1"><ns0:PublicationTimestamp>2024-02-03T11:45:52.068232</ns0:PublicationTimestamp><ns0:ParticipantRef>&#292;è&#318;ló</ns0:ParticipantRef><ns0:Description>UTF-8 to ISO-8859-1</ns0:Description><ns0:dataObjects/></ns0:PublicationDelivery>
```

2024-02-03 15:50 UTC, tefra commented
> ```python
> from xsdata.formats.dataclass.serializers import XmlSerializer
> from xsdata.formats.dataclass.serializers.config import SerializerConfig
> from netex import PublicationDelivery, MultilingualString, DataObjectsRelStructure
> from xsdata.models.datatype import XmlDateTime
> 
> import codecs
> 
> serializer_config = SerializerConfig(ignore_default_attributes=True)
> serializer_config.ignore_default_attributes = True
> serializer_config.xml_declaration = True
> serializer_config.encoding = 'ISO-8859-1'
> serializer = XmlSerializer(serializer_config)
> 
> publication_delivery = PublicationDelivery(
>     publication_timestamp=XmlDateTime.now(),
>     participant_ref="Ĥèľló",
>     description=MultilingualString(value="UTF-8 to ISO-8859-1"),
>     data_objects=DataObjectsRelStructure(choice=[]),
>     version="ntx:1.1",
> )
> 
> output = serializer.render(publication_delivery)
> 
> codecs.open('test.xml', 'w', encoding="ISO-8859-1").write(output)
> ```
> 
> Without codecs it outputs again in UTF-8. I think either we need a render which _guarantees_ binary output. Otherwise this results into a fake ISO-8859-1 header, with UTF-8 content:
> 
> ```
> <?xml version="1.0" encoding="ISO-8859-1"?>
> <ns0:PublicationDelivery xmlns:ns0="http://www.netex.org.uk/netex" version="ntx:1.1"><ns0:PublicationTimestamp>2024-02-03T11:45:52.068232</ns0:PublicationTimestamp><ns0:ParticipantRef>&#292;è&#318;ló</ns0:ParticipantRef><ns0:Description>UTF-8 to ISO-8859-1</ns0:Description><ns0:dataObjects/></ns0:PublicationDelivery>
> ```

Hrm, true, the proper way would be to get the encoding from the `:out TextIO`,  argument someone passes to the 
 `XmlSerializer.write` method, but that would limit people from simply passing `sys.stdout` as the output and still wanted to see the correct encoding in the xml header.

2024-02-03 15:53 UTC, skinkie commented
> Hrm, true, the proper way would be to get the encoding from the `:out TextIO`, argument someone passes to the `XmlSerializer.write` method, but that would limit people from simply passing `sys.stdout` as the output and still wanted to see the correct encoding in the xml header.

My personal use case is the output towards a webservice, which does have a text= or binary= option. Would need to figure out how to handle that use case.

2024-02-03 18:47 UTC, tefra commented
> > Hrm, true, the proper way would be to get the encoding from the `:out TextIO`, argument someone passes to the `XmlSerializer.write` method, but that would limit people from simply passing `sys.stdout` as the output and still wanted to see the correct encoding in the xml header.
> 
> My personal use case is the output towards a webservice, which does have a text= or binary= option. Would need to figure out how to handle that use case.

Ok I am not sure I follow and what do you expect the serializer to do about that use case?

2024-02-03 18:59 UTC, skinkie commented
> Ok I am not sure I follow and what do you expect the serializer to do about that use case?

I think we can both agree that everything in Python that pretends to be a string is in UTF-8. So if something explicitly shouldn't be UTF-8 it likely a binary representation, not to be touched thereafter. I think we want 'render' without the decode, is that 'write'?

2024-02-04 07:07 UTC, tefra commented
> > Ok I am not sure I follow and what do you expect the serializer to do about that use case?
> 
> I think we can both agree that everything in Python that pretends to be a string is in UTF-8. So if something explicitly shouldn't be UTF-8 it likely a binary representation, not to be touched thereafter. I think we want 'render' without the decode, is that 'write'?

So you want to add something to the serializers api? How do you imagine that to work, any references to other libraries in any language could be helpful.

2024-02-15 18:03 UTC, closed without merging